ihp/ihp_results/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('ihp_results.views',
    url(r'^import/(?P<agency_id>\d+)$', 'import_response', name="import_response"),

    url(r'^reports/entity/(?P<agency_id>\d+)/$', 'entity_report', name="ihp_entity_report"),
    url(r'^reports/entity/(?P<agency_id>\d+)/(?P<output_format>\w+)/$', 'entity_report', name="ihp_entity_report_output"),

    url(r'^reports/entity_indicator/(?P<scorecard_id>\d+)/(?P<identifier>\w+)/$', 'indicator_by_entity', name="scorecard_entity_indicator_report"),
    url(r'^reports/entity_indicator/(?P<scorecard_id>\d+)/(?P<identifier>\w+)/(?P<output_format>\w+)/$', 'indicator_by_entity', name="scorecard_entity_indicator_report_output"),

    url(r'^reports/grouped_indicator/(?P<scorecard_id>\d+)/(?P<data_series_group_name>\w+)/(?P<identifier>\w+)/$', 'indicator_by_group', name="scorecard_group_indicator_report"),
    url(r'^reports/grouped_indicator/(?P<scorecard_id>\d+)/(?P<data_series_group_name>\w+)/(?P<identifier>\w+)/(?P<output_format>\w+)/$', 'indicator_by_group', name="scorecard_group_indicator_report_output"),

)

ihp/ihp_results/forms.py
import re
from collections import defaultdict
from ordereddict import OrderedDict

from django import forms
from django.db.models import Q
from django.template.defaultfilters import slugify
from django.utils.translation import ugettext_lazy as _

from bootstrap.forms import *

from scorecard_processor.models.meta import DataSeries
from scorecard_processor.models.inputs import ResponseSet, Response, ResponseOverride
from scorecard_processor.models.outputs import OperationArgument

from plugins import register

class QuestionFieldset(Fieldset):
    def __init__(self, question_group, *fields):
        self.legend_html = question_group and ('<legend>%s</legend>' % question_group.i18n.name) or ''
        self.div_id = question_group and 'qg_'+slugify(question_group.pk);
        if not self.div_id:
            self.div_id = 'general'
        
        if question_group and question_group.help_text:
            self.legend_html += "<p class='legend'>%s</p>" % question_group.i18n.help_text
        self.fields = list(fields)

    def add_field(self, field):
        self.fields.append(field)

    def render_fields(self, form):
        fields = []
        for field in self.fields:
            if isinstance(field, dict):
                question = field['question']
                label="""<span class="identifier">%s.</span> 
                     <span class="question">%s</span>""" % (question.i18n.identifier,question.i18n.question)
                fields.append("""<div class='question_group row'>
                                    <label class="question">%s</label>
                                    %s
                                </div>""" % (label, form.render_fields(field['fields'])))
            else:
                fields.append(form.render_fields([field]))
        return ''.join(fields)

    def as_html(self, form):
        return u"<div class='tab-pane' id='%s'><fieldset>%s<div class='fields'>%s</div></fieldset></div>" % (self.div_id, self.legend_html, self.render_fields(form))

import plugins

class MultiYearDataException(Exception):
    pass

class QuestionForm(BootstrapForm):

    currency = forms.ChoiceField(
                    choices=plugins.CurrencySelector().widget.widgets[0].choices,
                    label=_("Currency"),
                    help_text=_("Please select your currency")
                ) 
    baseline_year = forms.ChoiceField(
                        choices=((2005, 2005), (2006,2006), (2007,2007)),
                        label=_("Baseline data"),
                    ) 
    current_year = forms.ChoiceField(
                        choices=((2011,2011), (2010,2010)),
                        label=_("Latest data"),
                    ) 

    def __init__(self, *args, **kwargs):
        self.entity = kwargs.pop('entity')
        self.survey = kwargs.pop('survey')
        self.user = kwargs.pop('user')
        self.series = OrderedDict([(s.pk,s) for s in kwargs.pop('series')])
        self.country = kwargs.pop('country')
        self.collection_year = defaultdict(list)
        try:
            self.static = kwargs.pop('static')
        except KeyError:
            self.static = False

        super(QuestionForm, self).__init__(*args, **kwargs)
        self.layout = []

        self.responsesets = list(self.entity.responseset_set.filter(data_series=self.country).filter(data_series__in=self.series.values()))
        response_dict = dict([(r.pk,r) for r in self.responsesets])
        self.response_types = dict([(r.get_data_series_by_type()['Data collection year'],r) for r in self.responsesets])
        self.responses = Response.objects.filter(
                        current=True,
                        response_set__in=self.responsesets).\
                    select_related('question')
        self.question_dict = defaultdict(dict)
        self.questions = {}
        self.response = {}

        if self.static:
            for fieldname in ['currency','baseline_year','current_year']:
               field = self.fields[fieldname]
               field.widget.attrs['readonly'] = 'readonly'
               field.widget.attrs['disabled'] = 'disabled'
               field.widget.attrs['class'] = 'hidden'
               field.required = False
            

        collection_lookup = {"Baseline":"baseline_year","2012 collection":"current_year"}
        for responseset in self.responsesets:
            currency = responseset.get_meta('currency')
            if currency and not self.initial.get('currency'):
                self.initial['currency'] = currency['value']

            ds_dict = responseset.get_data_series_by_type()
            self.collection_year[ds_dict['Data collection year']].append(ds_dict['Year'])
            field = self.fields[collection_lookup[ds_dict['Data collection year'].name]]
            field.widget.attrs['readonly'] = 'readonly'
            field.widget.attrs['disabled'] = 'disabled'
            field.required = False

        for response in self.responses:
            #Limit db hits for responsesets
            response.response_set = response_dict[response.response_set_id]
            ds_dict = response.response_set.get_data_series_by_type()
            self.question_dict[response.question][ds_dict['Data collection year']]=response

        for collection, year in self.collection_year.items():
            self.initial[collection_lookup[collection.name]] = year[0].name
            rs = self.response_types.get(collection)
            if rs and (rs.editable == False or self.static):
               field = self.fields[collection_lookup[collection.name]]
               field.widget.attrs['readonly'] = 'readonly'
               field.widget.attrs['disabled'] = 'disabled'
               field.widget.attrs['class'] = 'hidden'
               field.required = False

        series_list = self.series.values()
        current_series = series_list[0]
        series_list.reverse()

        for group in self.survey.questiongroup_set.all().select_related('question'):
            fieldset = QuestionFieldset(group)
            for question in group.question_set.all():
                label = True
                self.questions[question.pk] = question
                if question.widget == 'textbox':
                    self.add_field_from_question(question, current_series)
                    fieldset.add_field('q_%s_%s' % (question.pk, current_series.pk))
                else:
                    fields = []
                    for series in series_list:
                        rs = self.response_types.get(series)
                        self.add_field_from_question(question, series, False)
                        fields.append('q_%s_%s' % (question.pk, series.pk))
                    fieldset.add_field({'question':question, 'fields':fields})
            self.layout.append(fieldset)

        for question, series in self.question_dict.items():
            for ds, response in series.items():
                key = 'q_%s_%s' % (response.question.pk, ds.pk)
                if key not in self.initial:
                    self.initial[key] = response.get_value()
                    year = response.response_set.get_data_series_by_type()['Year']
                    if self.initial[key] and year.name != self.collection_year[ds][0].name:
                        #TODO: Breaks for checkbox questions
                        self.initial[key] = ' '.join([self.initial[key], '(%s)' % year])
                    self.response['q_%s_%s' % (response.question.pk, ds.pk)] = response
            
    def add_field_from_question(self, question, series, label=True):
        read_only = self.static
        rs = self.response_types.get(series)
        if rs and rs.editable == False:
            read_only=True
        field = register.get_input_plugin(question.widget).plugin
        if label:
            label="""<span class="identifier">%s.</span> 
                     <span class="question">%s</span>""" % (question.i18n.identifier,question.i18n.question)
        else:
            label = {
                    "Baseline":_("Baseline data"),
                    "2012 collection":_("Latest data"),
                }.get(series.name)
        if issubclass(field, forms.DateField):
            field = field(
                        help_text = question.i18n.help_text,
                        label = label,
                        required = False,
                        widget = field.widget(years=('2005','2006','2007','2008','2009','2010','2011','2012'))
            )
        else:
            field = field(
                        help_text = question.i18n.help_text,
                        label = label,
                        required = False,
            )
        if read_only:
            field.widget.attrs['readonly'] = 'readonly'
            field.widget.attrs['disabled'] = 'disabled'
            field.widget.attrs['class'] = 'hidden'
        self.fields['q_%s_%s' % (question.pk,series.pk)] = field

    def is_valid(self):
        matcher = re.compile(r'\((\d+)\)')
        data = self.data.copy()
        self.custom_year = getattr(self,'custom_year', {})
        for key in data.keys():
            field = data.getlist(key)
            year = None
            new_value = []
            for item in field:
                check = matcher.split(item)
                if len(check)>1:
                    year = check[1]
                    new_value.append(check[0])
                else:
                    new_value.append(item)
            data.setlist(key, new_value)
            if year:
                if len(key.split('_'))>3:
                    key = '_'.join(key.split('_')[:-1])
                self.custom_year[key] = year
        self.data = data
        return super(QuestionForm, self).is_valid()

    def save(self):
        collection_year = dict([(x.name,y[0].name) for x,y in self.collection_year.items()])

ihp/ihp_results/templates/ihp_results/add_dsg_survey.html
{% extends 'base.html' %}
{% load i18n %}
{% block head_title %}{% blocktrans with survey.i18n.name as survey_name and entity.name as entity_name%}Add a new response to {{survey_name}} for {{entity_name}}{% endblocktrans %}{% endblock %}
{% block fluid_content_outer %}
  <div class="container">
    <div class="content">
      <div class="page-header">
        <h1>{% blocktrans %}New response to{% endblocktrans %} {{survey.i18n.name}} <small>{% blocktrans %}for{% endblocktrans %} <a href="{{entity.get_absolute_url}}">{{entity.name}}</a></small></h1>
      </div>
      <div class="row">
        <div class="span14">
          {% if survey.short_description %}
            {{survey.i18n.short_description|safe}}
          {% else %}
            <h2>{% blocktrans %}Please select a country{% endblocktrans %}</h2>
          {% endif %}
          <ul>
          {% for ds in data_series %}
            <li><a href="{% url survey_dsg_response_edit entity.pk data_series_group.pk survey.pk ds.name %}">{{ds.name}}</a></li>
          {% endfor %}
          </ul>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

ihp/ihp_results/templates/ihp_results/edit_dsg_survey.html
{% extends 'base.html' %}
{% load i18n %}
{% block head_title %}{% blocktrans with survey.i18n.name as survey_name and entity.name as entity_name%}Response to {{survey_name}} for {{entity_name}}{% endblocktrans %}{% endblock %}
{% block script_bottom %}
{{block.super}}
<style>
  .legend.span5 {clear:left}
  .fields.span10 {float:right}
  label .identifier {margin-right:0.5em;}
  .form-stacked .clearfix div.input {clear:left;padding:5px 0 20px 20px}
  .input .currency {margin-right:0.5em;}
  select.currency_select {display:none}
  a.glossary_term {font-weight:bold;border-bottom:dotted 1px #386; color:#386;cursor:help}
  #definitions {position:fixed;top:0;left:0;width:100%;height:100%;background:#aaa;background:RGBA(95,95,95,0.5);z-index:1000;display:none}
  #definitions .term {display:none}
  .modal .modal-body {max-height: 300px; overflow:auto}
  .question_group {padding-left:20px}
  .question_group label.question {margin-bottom:10px;}
  .question_group > div {float:left;margin-left:20px;max-width:350px}

  .actions .btn {display:none}
    .start #continue {display:block}
    .normal #save_continue{display:block}
    .finish #save{display:block}
</style>
<script type="text/javascript">
$('input.hidden, select.hidden, textarea.hidden').each(function(i,e){
  //Hide form elements if they are disabled
  $(e).parent('div').parent('div').hide()
})
function set_currency(currency) {
  $('select.currency_select').each(function(i,e){
    $(e).val(currency);
  }) 
}
$('select#id_currency').change(function(e){
  set_currency($(e.target).val());
})
set_currency($('select#id_currency').val());

$('ul.tabs').tabs();
$('ul.tabs').bind('change', function (e) {
  //window.console.log() // activated tab
  var el=$('a',$($(e.target).parent()).next('li'))
  if (el.length) {
    var href=el.attr('href');
    $('#next').attr('value',href.substring(1));
  } else {
    $('#next').attr('value','');
  }
  var tab=$(e.target).parent()
  if (tab.attr('id') == 'intro_tab') {
    $('.actions').removeClass('normal');
    $('.actions').removeClass('finish');
    $('.actions').addClass('start');
  } else if (tab.hasClass('last_tab')) {
    $('.actions').removeClass('start');
    $('.actions').removeClass('normal');
    $('.actions').addClass('finish');
  } else {
    $('.actions').removeClass('start');
    $('.actions').removeClass('finish');
    $('.actions').addClass('normal');
  }
  parse_defs();
})
$('#continue').bind('click', function(e) {
  $($('.tabs li a')[1]).click();
  e.preventDefault();
})

next = false;
if (window.location.hash) {next = window.location.hash;}
if ($('.error').length) {
  next = '#'+$($('.error')[0]).parents('div.tab-pane').attr('id');
}

if (next) {
  $('a',next.replace('#','#t')).click();
}

var terms = Array();
$('.term').each(function (i,e) {
  terms.push({term:$(e).attr('data-term'), id:$(e).attr('id')})
})

function parse_defs() {
  var pane = $('.tab-pane.active')
  if ((pane.data('parsed_def')==undefined) && ($(terms).length)) {
    $('label, legend, div.intro', pane).each(function(i,e) {
      $(terms).each(function(j,f) {
        var test = $(e).html().split(f.term);
        if (test.length > 1) {
          var result = $(test.join("<a class='glossary_term' data-id='"+f.id+"' title='{% trans "Click to see definition" %}'>"+f.term+"</a>"));
          var join = true;
          $('.glossary_term', result).each(function(z,x){
            if ($(x).attr('data-id').indexOf('glossary_term')>0) {
              join = false;
              return false;
            }
          })
          if (join){
            $(e).html(result);
          }
          //Do we want to keep finding more defs?
        }
      });
    });
    pane.data('parsed_def',true);
  }
}

$('a.glossary_term').live({ 
  click:function(e) {
    $('#definitions').fadeIn('fast');
    $('#'+$(this).data('id')).modal('show');
  },
})
$('.modal a.close').live({click:function(e){
  $('#definitions').fadeOut('fast');
}})
$('#definitions').bind({click:function(e){
  $('.modal:visible a.close').click();
}})

$(document).ready(function () {
  parse_defs();
})

</script>
{% endblock %}

{% block fluid_content_outer %}
  <div class="container">
    <div class="content">
      <div class="page-header">
        <h1>{{survey.i18n.name}} <small>for <a href="{{entity.get_absolute_url}}">{{entity.name}}</a> - {{data_series}}</small></h1>
      </div>
      <form method="POST" class="form-stacked">
          {% csrf_token %}
          <div class="row">
            <div class="offset1 span13">
              <ul class="tabs">
                <li class="active" id="intro_tab"><a href="#intro">Overview</a></li>
                {% for group in survey.questiongroup_set.all %}
                  <li id="tqg_{{group.pk|slugify}}" class="{% if forloop.last %}last_tab{%endif %}"><a href="#qg_{{group.pk|slugify}}">{{forloop.counter}}</a></li>
                {% endfor %}
              </ul>
              <div class="form tab-content">
                <div class="tab-pane active" id="intro">
                  <p>{{survey.i18n.description|safe}}</p>
                  <div class="row">
                    <div class="span4">
                      <label>{{form.currency.label}}</label>
                      <div>{{form.currency}}</div>
                    </div>

                    <div class="span4">
                      <label>{{form.baseline_year.label}}</label>
                      <div>{{form.baseline_year}}</div>
                    </div>

                    <div class="span4">
                      <label>{{form.current_year.label}}</label>
                      <div>{{form.current_year}}</div>
                    </div>
                  </div>
                </div>
                {{form.as_div}}
              </div>
              <input type="hidden" id="next" name="next" value="" />
              <div class="actions start">
                  <p>{% blocktrans %}Download 2011 data <a target="_blank" href="http://ihpresults.net/results/data/">here</a>{% endblocktrans %}</p>
                  <button               id="continue" class="btn primary large pull-right">{% blocktrans %}Continue{%endblocktrans%}</button>
                  <button type="submit" id="save_continue" class="pull-right btn primary large">{% blocktrans %}Save and continue{% endblocktrans %}</button> &nbsp;
                  <button type="submit" id="save" class="pull-right btn primary large">{% blocktrans %}Save and submit{% endblocktrans %}</button> &nbsp;
              </div>
            </div>
            
          </div>
      </form>
    </div>
  </div>

  <div id="definitions" style="display:none">
      {% for term in entity.project.get_glossary %}
        <div class='modal term' id="{{term.term|slugify}}" data-term="{{term.term}}" data-position="center center">
          <div class="modal-header">
            <a class="close" href="#">×</a>
            <h3>{{term.term}}</h3>
          </div>
          <div class="modal-body">{{term.definition.definition|linebreaksbr|urlize}}</div>
        </div>
      {% endfor %}
  </div>
{% endblock %}

ihp/ihp_results/templates/ihp_results/entity_report.html
{% extends 'base.html' %}
{% block head_title %}Report results - {{entity.name}}{% endblock %}
{% block script_bottom %}
{{block.super}}
<script type="text/javascript">
  $(function() {
    $('dl.concat').each(function (i,e) {      
      var data = $($(e).parent()).html();
      var a = $('<a rel="popover" class="label" title="Responses">...</a>');
      a.attr('data-content', data);
      $($(e).parent()).append(a);
      $(e).remove();
    })

    $('[rel=popover]').popover({html:true,live:true});
  });
</script>

{% endblock %}
{% block fluid_content_outer %}
  <style>
    caption {font-size:large;text-align:left;margin:10px 0}
    table {margin-bottom:40px;}
    table td {text-align:center}
    thead th {text-align:center}
    td a.label {cursor:help}
    .popover .inner {width:500px;}
    td dl.concat {width:120px;}
  </style>
  <div class="fluid-container">
    <div class="content">
      <div class="page-header">
        <h1><a href="{{entity.get_absolute_url}}">{{entity.name}}</a> results</h1>
      </div>
      <table style="width:auto" class="bordered-table zebra-striped condensed-table">
        {% for operation, items in data.items %}
          {% if forloop.counter == 1 %}
            <thead>
              <tr>
                <th></th>
                {% for series, v in items %}
                   <th colspan={{v|length}}>{{series.name}}</th>
                {% endfor %}
              </tr>
              <tr>
                <th>Operation</th> 
                {% for country, data in items %}
                  {% for series, v in data %}
                   <th>{{series.name}}</th>
                  {% endfor %}
                {% endfor %}
              </tr>
            </thead>
            <tbody>
          {% endif %}
          <tr>
            <th title="{{operation.description}}">{{operation.identifier}}</th>
            {% for country, data in items %}
              {% for series, v in data %}
               <td>{% if v %}{{v.as_html}}{% endif %}</td>
              {% endfor %}
            {% endfor %}
          </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
{% endblock %}

ihp/ihp_results/templates/ihp_results/import_response.html
{% extends 'base.html' %}
{% block head_title %}Import a survey response{% endblock %}
{% block fluid_content_outer %}
  <div class="container">
    <div class="content">
      <div class="page-header">
        <h1>Import response</h1>
      </div>
      <div class="row">
          <div class="span14">
            <form method=POST enctype="multipart/form-data" class="form-stacked">
              {% csrf_token %}
              {{form}}
              <div class="actions">
                <button class="btn primary" type="submit">Import</button>
              </div>
            </form>
          </div>
      </div>
    </div>
  </div>
{% endblock %}

ihp/ihp_results/templates/ihp_results/view_dsg_survey.html
{% extends 'base.html' %}
{% load i18n %}
{% block head_title %}{% blocktrans with survey.i18n.name as survey_name and entity.name as entity_name%}Response to {{survey_name}} for {{entity_name}}{% endblocktrans %}{% endblock %}
{% block script_bottom %}
{{block.super}}
<style>
  .legend.span5 {clear:left}
  .fields.span10 {float:right}
  label .identifier {margin-right:0.5em;}
  .form-stacked .clearfix div.input {clear:left;padding:5px 0 20px 20px}
  .input .currency {margin-right:0.5em;}
  select.currency_select {display:none}
  a.glossary_term {font-weight:bold;border-bottom:dotted 1px #386; color:#386;cursor:help}
  #definitions {position:fixed;top:0;left:0;width:100%;height:100%;background:#aaa;background:RGBA(95,95,95,0.5);z-index:1000;display:none}
  #definitions .term {display:none}
  .modal .modal-body {max-height: 300px; overflow:auto}
  .question_group {padding-left:20px}
  .question_group label.question {margin-bottom:10px;}
  .question_group > div {float:left;margin-left:20px;max-width:350px}

  .actions .btn {display:none}
    .start #continue {display:block}
    .normal #save_continue{display:block}
    .finish #save{display:block}
</style>
<style media="print">
  .topbar {display:none}
  body {padding-top:0}
</style>
{% endblock %}

{% block fluid_content_outer %}
  <div class="container">
    <div class="content">
      <div class="page-header">
        <h1>{{survey.i18n.name}} <small>for <a href="{{entity.get_absolute_url}}">{{entity.name}}</a> - {{data_series}}</small></h1>
        <form><input class="btn primary pull-right" type="button" value="{% trans "Print this page" %}" onclick="window.print();return false;" /></form> 
      </div>
      <form method="POST" class="form-stacked">
          {% csrf_token %}
          <div class="row">
            <div class="offset1 span4">
              <label>{{form.currency.label}}</label>
              <div>{{form.currency}}</div>
            </div>

            <div class="span4">
              <label>{{form.baseline_year.label}}</label>
              <div>{{form.baseline_year}}</div>
            </div>

            <div class="span4">
              <label>{{form.current_year.label}}</label>
              <div>{{form.current_year}}</div>
            </div>
          </div>
          <div class="row" style="margin-top:30px">
            <div class="offset1 span13">
              {{form.as_div}}
            </div>
          </div>
      </form>
    </div>
  </div>

{% endblock %}