ihp/ihp_results/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('ihp_results.views',
    url(r'^import/(?P<agency_id>\d+)$', 'import_response', name="import_response"),

    url(r'^reports/entity/(?P<agency_id>\d+)/$', 'entity_report', name="ihp_entity_report"),
    url(r'^reports/entity/(?P<agency_id>\d+)/(?P<output_format>\w+)/$', 'entity_report', name="ihp_entity_report_output"),

    url(r'^reports/entity_indicator/(?P<scorecard_id>\d+)/(?P<identifier>\w+)/$', 'indicator_by_entity', name="scorecard_entity_indicator_report"),
    url(r'^reports/entity_indicator/(?P<scorecard_id>\d+)/(?P<identifier>\w+)/(?P<output_format>\w+)/$', 'indicator_by_entity', name="scorecard_entity_indicator_report_output"),

    url(r'^reports/grouped_indicator/(?P<scorecard_id>\d+)/(?P<data_series_group_name>\w+)/(?P<identifier>\w+)/$', 'indicator_by_group', name="scorecard_group_indicator_report"),
    url(r'^reports/grouped_indicator/(?P<scorecard_id>\d+)/(?P<data_series_group_name>\w+)/(?P<identifier>\w+)/(?P<output_format>\w+)/$', 'indicator_by_group', name="scorecard_group_indicator_report_output"),

)

ihp/ihp_results/models.py
from django.db import models
from scorecard_processor.models import Entity

import reports
import plugins

def attachment_storage(instance, filename):
    return 'entity_attachments/%s/%s' % (instance.entity.pk, filename)

class Attachment(models.Model):
    #Possibly store metadata about the files/attachment?
    entity = models.ForeignKey(Entity)
    submission_date = models.DateTimeField(auto_now_add=True)
    file = models.FileField(upload_to=attachment_storage, help_text="Upload a new file")

    class Meta:
        ordering = ('-submission_date',)

    def __unicode__(self):
        return u'%s on %s' % (self.file, self.entity)

    @property
    def filename(self):
        return self.file.name.split('/')[-1]

    @property
    def extension(self):
        return self.filename.split('.')[-1]

ihp/ihp_results/templates/scorecard_processor/_entity_responsesets.html
{% load guardian_tags i18n %}
<ul>
{% regroup responsesets by get_data_series_by_type.Country as responses %}
{% for response in responses %}
  {% get_obj_perms user for response.grouper as "perms" %}
  {% if "can_use" in perms or "can_view" in perms %}
    <li class="responseset" name="responseset_{{response.grouper.name}}">
      {% if "can_use" in perms %}
        <a href="{% url survey_dsg_response_edit object.pk "Country" response.list.0.survey_id response.grouper.name %}">
      {% endif %}
      {{response.grouper.name}}
      {% if "can_use" in perms %}</a>{% endif %}
      {% if "can_view" in perms %}
        (<a href="{% url survey_dsg_response_view object.pk "Country" response.list.0.survey_id response.grouper.name %}">{% trans "view response" %}</a>)
      {% endif %}
    </li>
  {% endif %}
{% endfor %}
</ul>
{% if user.is_staff %}<a href="{% url import_response object.pk %} " class="btn">Import response</a>{% endif %}
{% if object.attachment_set.count %}
<h3>Previous uploads</h3>
  <ul>
  {% for attachment in object.attachment_set.all %}
    <li><a href="{{MEDIA_URL}}{{attachment.file}}">{{attachment.filename}}</a><br /><small>Submitted: {{attachment.submission_date}}</small></li>
  {% endfor %}
  </ul>
{% endif %}

ihp/ihp_results/templates/scorecard_processor/_project_entity_display.html
<li><a href="{{entity.get_absolute_url}}">{% if entity.abbreviation %}{{entity.abbreviation}} - {% endif %}{{entity.name}}</a> (<a href="{% url ihp_entity_report entity.pk %}">report</a>)</li>

ihp/ihp_results/templates/scorecard_processor/_project_scorecard_reports.html
Entity by indicator:
<p>
{% for indicator in scorecard.operation_set.indicators %}
  <a href="{% url scorecard_entity_indicator_report scorecard.pk indicator.identifier %}">{{indicator.identifier}}</a>, 
{% endfor %}
</p>
Country by indicator:
<p>
{% for indicator in scorecard.operation_set.indicators %}
  <a href="{% url scorecard_group_indicator_report scorecard.pk "Country" indicator.identifier %}">{{indicator.identifier}}</a>, 
{% endfor %}
</p>

ihp/ihp_results/templates/scorecard_processor/_render_survey_link.html
<a class="btn" style="margin-bottom:10px" href="{% url survey_dsg_response entity.pk "Country" survey.pk %}">{{survey.i18n.name}}</a>

ihp/ihp_results/templates/scorecard_processor/project_detail.html
{% extends 'base.html' %}
{% block head_title %}Survey selection for {{object.name}}{% endblock %}
{% block fluid_content_outer %}
  <style>
    .entity {
      margin-bottom:8px
    }
  </style>
  <div class="container">
    <div class="content">
      <div class="page-header">
        <h1>{{object.name}} <small>manage surveys</small></h1>
      </div>
      <div class="row">
        <div class="span8">
          <div class="row">
            
            <h3 class="span8">Data by agency/gov</h3>
            {% regroup object.entity_set.all by entity_type.plural as entity_list %}
            {% for entity_type in entity_list %}
              <h4 class="span8">{{entity_type.grouper|capfirst}}</h4>
              {% for entity in entity_type.list %}
                <div class="span2 entity">
                  {{entity.abbreviation}}<br />
                  <a href="{{entity.get_absolute_url}}">Responses</a> <br />
                  <a href="{% url ihp_entity_report entity.pk %}">Graph & Table</a>
                </div>
              {% endfor %}
            {% endfor %}
          </div>
        </div>
        <div class="span8">
          <h3>Surveys</h3>
            
            <ul>
            {% for survey in object.survey_set.all %}
              {% if survey.active %}<li><a href="{{survey.get_absolute_url}}">{{survey.name}}</a> (<a href="{{survey.get_absolute_url}}responses/">view {% with survey.responseset_set.count as count %}{{count}} response{{count|pluralize}}{% endwith %}</a>)</li>{% endif %}
            {% endfor %}
            </ul>
            <div class="row">
              <div class="span8"> 
                <h3>Scorecards & Aggregate reports</h3>
                  <ul>
                  {% for scorecard in object.scorecard_set.visible %}
                    <li>{{scorecard.name}} (<a href="{{scorecard.get_absolute_url}}">view logic</a>)<br />
                    Reports: 
                    <ul>
                    {% for report in scorecard.reportrun_set.all %}
                      <li><a href="{{report.get_absolute_url}}run/">{{report.name}}</a></li>
                    {% endfor %}
                    </ul>

                    All partner data by indicator:
                    <p>
                    {% for indicator in scorecard.operation_set.indicators %}
                      <a href="{% url scorecard_entity_indicator_report scorecard.pk indicator.identifier %}">{{indicator.identifier}}</a>, 
                    {% endfor %}
                    </p>
                    All country data by indicator:
                    <p>
                    {% for indicator in scorecard.operation_set.indicators %}
                      <a href="{% url scorecard_group_indicator_report scorecard.pk "Country" indicator.identifier %}">{{indicator.identifier}}</a>, 
                    {% endfor %}
                    </p>
                    </li>
                  {% endfor %}
                  </ul>
              </div>
            </div>
            <div class="row">
              <div class="span8"> 
                <h3>Other Reports</h3>
                  <ul>
                  {% for link, name in object.get_report_links %}
                    <li><a href="{{link}}">{{name}}</a><br />
                  {% endfor %}
                  </ul>
              </div>
            </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}