django-scorecard-processor/scorecard_processor/urls.py
from django.conf.urls.defaults import *
from django.conf import settings
from django.views.generic.list_detail import object_list, object_detail
from django.views.generic.create_update import create_object, update_object
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.models import User

from models import Entity, Project, Survey, Question, Scorecard, ReportRun
entity_qs = Entity.objects.all().select_related('entity_type')
project_qs = Project.objects.all()
survey_qs = Survey.objects.all()
question_qs = Question.objects.all()
scorecard_qs = Scorecard.objects.all()
reportrun_qs = ReportRun.objects.all()
user_qs = User.objects.exclude(pk=settings.ANONYMOUS_USER_ID)

from views import SurveyResponses
from views import SurveyOverrides, ResponseOverrideView, ResponseOverrideDelete, create_override
from views import UserView
from views import entity_add_user, entity_remove_user
from reports import get_entity_urls, get_project_urls

urlpatterns = patterns('scorecard_processor.views',
    url(r'^$', 'index', name="scorecard_index"),

#Projects, surveys and scorecards
#TODO:limit entities to the ones a user account can access
    url(r'^project/$', 
        login_required(object_list), 
        {'queryset':project_qs},
        name="project_list"
    ), 
    url(r'^project/(?P<object_id>\d+)/$', 
        login_required(object_detail),
        {'queryset':project_qs}, 
        name="show_project"
    ),


#Manage surveys
    url(r'^project/(\d+)/survey/(?P<object_id>\d+)/$', 
        login_required(object_detail),
        {'queryset': survey_qs}, 
        name="show_survey"
    ),

#Survey overrides
    url(r'^project/(\d+)/survey/(?P<survey_id>\d+)/override/add/$', 
        login_required(SurveyOverrides.as_view()),
        {'queryset': survey_qs}, 
        name="add_response_override"
    ),

    url(r'^project/(\d+)/survey/(\d+)/override/add/(?P<question_id>\d+)/$', 
        create_override,
        {}, 
        name="add_response_override_question"
    ),

    url(r'^project/(\d+)/survey/(\d+)/override/(?P<override_id>\d+)/$', 
        login_required(object_detail),
        {'queryset': survey_qs}, 
        name="view_response_override"
    ),

    url(r'^project/(\d+)/survey/(\d+)/override/(?P<override_id>\d+)/remove/$', 
        login_required(object_detail),
        {'queryset': survey_qs}, 
        name="remove_response_override"
    ),

#Survey responses
    url(r'^project/(\d+)/survey/(?P<object_id>\d+)/responses/$', 
        login_required(SurveyResponses.as_view()),
        name="show_survey_responses"
    ),

    url(r'^project/(\d+)/survey/(?P<object_id>\d+)/responses/series/(?P<series>[\w\ ]+)/$', 
        login_required(SurveyResponses.as_view()),
        name="show_survey_responses_series"
    ),

    url(r'^project/(\d+)/survey/(?P<object_id>\d+)/responses/entity/(?P<entity>\d+)/$', 
        login_required(SurveyResponses.as_view()),
        name="show_survey_responses_entity"
    ),


# Manage scorecards
    url(r'^project/(\d+)/scorecard/(?P<object_id>\d+)/$',
        login_required(object_detail),
        {'queryset': scorecard_qs}, 
        name="show_scorecard"
    ),

# Users
    url(r'^users/$',
        staff_member_required(object_list),
        {'queryset': user_qs}, 
        name="user_list"
    ),
    url(r'^users/(?P<pk>\d+)/$',
        staff_member_required(UserView.as_view()),
        name="show_user"
    ),

#Reports
    url(r'^project/(\d+)/reports/generic/(?P<object_id>\d+)/$',
        login_required(object_detail),
        {'queryset': reportrun_qs}, 
        name="show_report"
    ),
    url(r'^project/(\d+)/reports/generic/(?P<object_id>\d+)/run/$',
        "run_report",
        name="run_report"
    ),
    url(r'^project/(\d+)/reports/generic/(?P<object_id>\d+)/run/(?P<output_format>\w+)/$',
        "run_report",
        name="run_report"
    ),
    url(r'^project/(?P<project_id>\d+)/reports/', 
        include(get_project_urls())
    ),


#Response side
    url(r'^entity/$', #TODO:limit entities to the ones a user account can access
        'entity_list',
        name="entity_list"
    ), 
    url(r'^entity/(?P<object_id>\d+)/$', 
        'entity_detail',
        name="show_entity"
    ),
    #Entity user management
    url(r'^entity/(?P<entity_id>\d+)/users/add/$', 
        entity_add_user,
        name="entity_add_user"
    ),
    url(r'^entity/(?P<entity_id>\d+)/users/(?P<user_id>\d+)/remove/$', 
        entity_remove_user,
        name="entity_remove_user"
    ),

    url(r'^entity/(?P<entity_id>\d+)/reports/', 
        include(get_entity_urls())
    ),
    url(r'^entity/(?P<object_id>\d+)/survey/add/(?P<survey_id>\d+)/$','add_survey',name="survey_response"),
    #TODO: urls for responses per survey
    url(r'^entity/(?P<object_id>\d+)/response/(?P<responseset_id>\d+)/edit/$','edit_survey',name="survey_response_edit"),

)

django-scorecard-processor/scorecard_processor/models/meta.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import translation


class Project(models.Model):
    name = models.CharField(max_length=100) 
    class Meta:
        app_label = "scorecard_processor"
        permissions = (
                        ("can_view", "Can view the project"),
                    )

    def _as_dict(self):
        return {'name':self.name}

    @models.permalink
    def get_absolute_url(self):
        return ('show_project',[str(self.pk)])

    def __unicode__(self):
        return "Project: %s" % (self.name)

    def get_report_links(self):
        from scorecard_processor import reports
        links = []
        for name, report in reports.get_project_reports():
            links.extend(report().get_report_links(self))
        return links

    def get_glossary(self):
        lang = translation.get_language()
        return GlossaryTerm.objects.filter(definition__lang=lang).select_related('definition')
        

class GlossaryDefinition(models.Model):
    project = models.ForeignKey(Project)
    definition = models.TextField() 
    lang = models.CharField(max_length=5, db_index=True)
    class Meta:
        app_label = "scorecard_processor"

    def __unicode__(self):
        return ", ".join([t.term for t in self.glossaryterm_set.all()] or [self.definition[:10]+'...'])

class GlossaryTerm(models.Model):
    term = models.CharField(max_length=200)
    definition = models.ForeignKey(GlossaryDefinition)
    class Meta:
        app_label = "scorecard_processor"

    def __unicode__(self):
        return self.term

# WIP for db based cache of which objects/fields need translation
#class GlossaryCache(models.Model):
#    obj = Generic...
#    term_set = ManyToManyField(GlossaryTerm)


class DataSeriesGroup(models.Model):
    name = models.CharField(max_length=30,primary_key=True)
    project = models.ForeignKey(Project)
    reverse_ordering = models.BooleanField(default=False)
    class Meta:
        ordering = ('name',)
        app_label = "scorecard_processor"

    def _as_dict(self):
        return {'name':self.name}

    def get_dataseries(self):
        qs = self.dataseries_set.filter(visible=True)
        if self.reverse_ordering:
            qs = qs.order_by('-name')
        return qs


    def __unicode__(self):
        return self.name

class DataSeries(models.Model):
    name = models.CharField(max_length=100)
    group = models.ForeignKey(DataSeriesGroup)
    visible = models.BooleanField(default=True)

    class Meta:
        verbose_name_plural = 'Data Series'
        ordering = ('-group','name')
        app_label = "scorecard_processor"
        permissions = (
                        ("can_use", "Can use the DataSeries"),
                        ("can_view", "Can view the DataSeries"),
                    )

    def _as_dict(self):
        return {'name':self.name}

    @property
    def data_type(self):
        return self.group_id

    def __unicode__(self):
        return "%s: %s" % (self.group.pk, self.name)

class EntityType(models.Model):
    name = models.CharField(max_length=30,primary_key=True)
    plural = models.CharField(max_length=30)
    project = models.ForeignKey(Project)
    class Meta:
        app_label = "scorecard_processor"
    def __unicode__(self):
        return "%s / %s" % (self.name, self.plural)


class Entity(models.Model):
    """
    An entity / organisation
    """
    name = models.CharField(max_length=100) 
    abbreviation = models.CharField(max_length=30, blank=True, null=True)
    entity_type = models.ForeignKey(EntityType)
    project = models.ForeignKey(Project)

    class Meta:
        app_label = "scorecard_processor"
        unique_together = (('name','project'),)
        ordering = ('entity_type','name')
        permissions = (
                        ("can_view", "Can view the Entity"),
                    )

    def _as_dict(self):
        return {
                'name':self.name,
                'abbreviation':self.abbreviation,
                'entity_type':self.entity_type_id,
            }

    @property
    def data_type(self):
        return self.entity_type.pk

    def get_response_set(self, survey, data_series):
        qs = self.responseset_set.filter(survey=survey)
        for ds in data_series:
            qs = qs.filter(data_series=ds)
        if len(qs) == 0:
            return None
        if len(qs) == 1:
            return qs[0]
        return qs

    @models.permalink
    def get_absolute_url(self):
        return ('show_entity',(str(self.pk),))

    def get_report_links(self):
        from scorecard_processor import reports
        links = []
        for name, report in reports.get_entity_reports():
            links.extend(report().get_report_links(self))
        return links

    def __unicode__(self):
        if self.abbreviation:
            return "%s: %s (%s)" % (self.entity_type.pk.capitalize(), self.name, self.abbreviation)
        return "%s: %s" % (self.entity_type.pk.capitalize(), self.name)

django-scorecard-processor/scorecard_processor/templates/scorecard_processor/_entity_responsesets.html
                <ul>
                {% for responseset in responsesets %}
                  <li class="responseset" name="responseset_{{responseset.pk}}"><a href="{{responseset.get_absolute_url}}">{% for series in responseset.get_data_series %}{{series.name}}{% if forloop.revcounter0 %}, {% endif %}{% endfor %}</a><br/> <strong>last update:</strong> {{responseset.last_update}}<br /> <strong>survey:</strong> {{responseset.survey.name}}</li>
                {% endfor %}
                </ul>

django-scorecard-processor/scorecard_processor/templates/scorecard_processor/_project_entity_display.html
              <li><a href="{{entity.get_absolute_url}}">{% if entity.abbreviation %}{{entity.abbreviation}} - {% endif %}{{entity.name}}</a></li>

django-scorecard-processor/scorecard_processor/templates/scorecard_processor/_render_survey_link.html
<a class="btn" style="margin-bottom:10px" href="{% url survey_response entity.pk, survey.pk %}">{{survey.i18n.name}}</a>

django-scorecard-processor/scorecard_processor/templates/scorecard_processor/entity_detail.html
{% extends 'base.html' %}
{% load i18n %}
{% block head_title %}Entity selection{% endblock %}
{% block script_bottom %}
{{block.super}}
<script type="text/javascript">
  if(document.location.hash) {
    $('li[name='+document.location.hash.replace('#','')+']').addClass("alert-message ");
    if ($('li[name='+document.location.hash.replace('#','')+']').length) {
      $('.add_more').addClass('alert-message');
    }
  }
</script>
{% endblock %}
{% block fluid_content_outer %}
<style>
  li.responseset {margin-bottom:10px}
  .add_more.alert-message h3,
  .add_more.alert-message p {display:block}

  .add_more h3,
  .add_more p {display:none}
</style>
  <div class="container">
    <div class="content">
      <div class="page-header">
        <h1>{% trans "Survey Responses" %} <small>{% trans "for" %} {{object.name}}</small></h1>
      </div>
      <div class="row">
      </div>
      <div class="row">
          <div class="span7">
            <h2>Respond <small>Click a button to add a new response</small></h2>
            <div class="add_more block-message success">
              <h3>{% trans "Thanks for your submission" %}</h3>
              <p>{% trans "You can add another response using this button:" %}</p>
              <div class="alert-actions">
            {% with object.entity_type.survey_set.active as survey_set %}
              {% if survey_set.count == 1 %}
                {% include 'scorecard_processor/_render_survey_link.html' with entity=object survey=survey_set.0 %}
              {% else %}
                <ul>
                  {% for survey in survey_set %}
                    <li>{% include 'scorecard_processor/_render_survey_link.html' with entity=object survey=survey %}</li>
                  {% endfor %}
                </ul>
              {% endif %}
            {% endwith %}
              </div>
            </div>

            <h2 style="padding-top:10px">{% trans "Associated users" %}</h2>
            {% if user_set == 0 %}
              <p>No users are currently associated with this {{object.entity_type}}</p>
            {% else %}
              <ul>
                {% for person in user_set %}
                  <li>{% if user.is_staff %}[<a href="{% url entity_remove_user object.pk person.pk %}" title="Remove access">x</a>] <a href="{% url show_user person.pk %}" title="Manage user">{% endif %}{{person.get_full_name}}{% if user.is_staff %}</a>{% endif %} <strong>{{person.email}}</strong></li>
                {% endfor %}
              </ul>
            {% endif %}
            {% if user.is_staff %}
              <p><a href="{% url entity_add_user object.pk %}">Add user by email address</a></p>
            {% endif %}
            {% comment %}
              <h2>View Reports</h2>
              <ul>
              {% for link, name in object.get_report_links %}
                <li><a href="{{link}}">{{name}}</a></li>
              {% endfor %}
              </ul>
            {% endcomment %}
          </div>
          {% with object.responseset_set.all.select_related as responsesets %}
              <div class="span7">
                <h2>{% trans "Edit responses" %} <small>{% trans "ordered by last update" %}</small></h2>
                {% include 'scorecard_processor/_entity_responsesets.html' %}
              </div>
          {% endwith %}
      </div>
    </div>
  </div>
{% endblock %}

django-scorecard-processor/scorecard_processor/templates/scorecard_processor/entity_list.html
{% extends 'base.html' %}
{% load guardian_tags %}
{% block head_title %}Entity selection{% endblock %}
{% block fluid_content_outer %}
  <div class="container">
    <div class="content">
      <div class="page-header">
        <h1>Choose an entity</h1>
      </div>
      <div class="row">
          {% if user.is_staff %}
            {% regroup object_list by entity_type.plural as entity_list %}
            {% for entity_type in entity_list %}
              <div class="span7">
                <h2>{{entity_type.grouper|capfirst}}</h2>
                <ul>
                {% for entity in entity_type.list %}
                  <li><a href="{{entity.get_absolute_url}}">{% if entity.abbreviation %}{{entity.abbreviation}} - {% endif %}{{entity.name}}</a></li>
                {% endfor %}
                </ul>
              </div>
            {% endfor %}
          {% else %}
            <div class="span7">
              <ul>
              {% for entity in object_list %}
                  <li><a href="{{entity.get_absolute_url}}">{% if entity.abbreviation %}{{entity.abbreviation}} - {% endif %}{{entity.name}}</a></li>
              {% endfor %}
              </ul>
            </div>
          {% endif %}
      </div>
    </div>
  </div>
{% endblock %}

django-scorecard-processor/scorecard_processor/templates/scorecard_processor/index.html
{% extends 'base.html' %}
{% block head_title %}Scorecard home{% endblock %}
{% block fluid_content_outer %}
  <div class="container">
    <div class="content">
      <div class="page-header">
        <h1>Manage scorecards, projects and responses</h1>
      </div>
      <div class="row">
        <div class="span10">
          <a href="project/">Create surveys and scorecards</a><br />
          <a href="entity/">Respond to surveys</a><br />
        </div>
        <div class="span4 sidebar">
          Sidebar of awkwardness
        </div>
      </div>
    </div>
  </div>
{% endblock %}

django-scorecard-processor/scorecard_processor/templates/scorecard_processor/project_detail.html
{% extends 'base.html' %}
{% block head_title %}Survey selection for {{object.name}}{% endblock %}
{% block fluid_content_outer %}
  <div class="container">
    <div class="content">
      <div class="page-header">
        <h1>{{object.name}} <small>manage surveys</small></h1>
      </div>
      <div class="row">
        <div class="span6">
          <h3>Data Series <a class="btn small" href="/admin/scorecard_processor/dataseriesgroup/add/">+</a></h3>
            {% for series in object.dataseriesgroup_set.select_related %}
            <dl>
              <dt class="label {% if series.name == "Country" %}notice{% endif %}">{{series.name}} <a class="" href="/admin/scorecard_processor/dataseriesgroup/{{series.pk}}/">edit</a></dt>
              <dd>
                {% for item in series.get_dataseries %}
                  {{item.name}}{% if forloop.revcounter0 %}, {% endif %}
                {% endfor %}
              </dd>
            </dl>
            {% endfor %}
        </div>
        <div class="span8 well">
          <h3>Surveys <a class="btn small" href="/admin/scorecard_processor/survey/add/">+</a></h3>
            
            <ul>
            {% for survey in object.survey_set.all %}
              <li>{% if not survey.active %}<span class="label" title="Users cannot submit responses">inactive</span>{% endif %} <a href="{{survey.get_absolute_url}}">{{survey.name}}</a> (<a href="{{survey.get_absolute_url}}responses/">view {% with survey.responseset_set.count as count %}{{count}} response{{count|pluralize}}{% endwith %}</a>)</li>
            {% endfor %}
            </ul>
            <div class="row">
              <div class="span8"> 
                <h3>Scorecards <a class="btn small" href="/admin/scorecard_processor/scorecard/add/">+</a></h3>
                  <ul>
                  {% for scorecard in object.scorecard_set.visible %}
                    <li><a href="{{scorecard.get_absolute_url}}">{{scorecard.name}}</a><br />
                    Reports: 
                    <ul>
                    {% for report in scorecard.reportrun_set.all %}
                      <li><a href="{{report.get_absolute_url}}">{{report.name}}</a> (<a href="{{report.get_absolute_url}}run/">view output</a>)</li>
                    {% endfor %}
                    </ul>
                    {% include "scorecard_processor/_project_scorecard_reports.html" %}
                    </li>
                  {% endfor %}
                  </ul>
              </div>
            </div>
            <div class="row">
              <div class="span8"> 
                <h3>Other Reports</h3>
                  <ul>
                  {% for link, name in object.get_report_links %}
                    <li><a href="{{link}}">{{name}}</a><br />
                  {% endfor %}
                  </ul>
              </div>
            </div>
        </div>
      </div>
      <div class="row">
          <h3>Entities <a class="btn small" href="/admin/scorecard_processor/entity/add/">+</a></h3>
          {% regroup object.entity_set.all by entity_type.plural as entity_list %}
          {% for entity_type in entity_list %}
          <div class="span7">
            <h2>{{entity_type.grouper|capfirst}}</h2>
            <ul>
            {% for entity in entity_type.list %}
              {% include 'scorecard_processor/_project_entity_display.html' %}
            {% endfor %}
            </ul>
          </div>
          {% endfor %}

        </div>
    </div>
  </div>
{% endblock %}

django-scorecard-processor/scorecard_processor/templates/scorecard_processor/project_list.html
{% extends 'base.html' %}
{% block head_title %}Project selection{% endblock %}
{% block fluid_content_outer %}
  <div class="container">
    <div class="content">
      <div class="page-header">
        <h1>Choose a project</h1>
      </div>
      <div class="row">
        <div class="span14">
          <ul>
          {% for entity in object_list %}
            <li><a href="{{entity.get_absolute_url}}">{{entity}}</a></li>
          {% endfor %}
          </ul>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

django-scorecard-processor/scorecard_processor/templates/scorecard_processor/reportrun_detail.html
{% extends 'base.html' %}
{% block head_title %}Report results - {{object.name}}{% endblock %}
{% block fluid_content_outer %}
  <div class="container">
    <div class="content">
      <div class="page-header">
        <h1>{{object.name}} <small>from <a href="{{object.scorecard.project.get_absolute_url}}">{{object.scorecard.project.name}}</a></small></h1>
      </div>
      <div class="row">
        <div class="span7">
          <h2>Derived from</h2>
          {% for group, responsesets in object.get_responsesets.items %}
            <h3>{{group}}</h3>
            <ul>
              {% for responseset in responsesets %}
                <li>
                  <a href="{{responseset.get_absolute_url}}"><strong>{{responseset.entity}}</strong><br />{{responseset.survey.name}}</a><br />
                  Data series: {% for series in responseset.data_series.all %}{{series.name}}{% if forloop.revcounter0 %}, {% endif %}{% endfor %}<br />
                </li>
              {% endfor %}
            </ul>
          {% endfor %}
        </div>
        <div class="span7">
          <h2><a href="run/">View report online</a></h2>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

django-scorecard-processor/scorecard_processor/templates/scorecard_processor/reportrun_run.html
{% extends 'base.html' %}
{% block head_title %}Report results - {{object.name}}{% endblock %}
{% block script_bottom %}
{{block.super}}
<script type="text/javascript" src="{{STATIC_URL}}js/jquery.tablesorter.min.js"></script>
<script type="text/javascript">

  

  $(function() {
    /* Initialize dynamic elements */
    $("table").tablesorter({ sortList: [[0,0]] });

    $('dl.concat').each(function (i,e) {      
      var data = $($(e).parent()).html();
      var a = $('<a rel="popover" class="label" title="Responses">...</a>');
      a.attr('data-content', data);
      $($(e).parent()).append(a);
      $(e).remove();
    })

    $('[rel=popover]').popover({html:true,live:true});

    /* Normalize the width of all table elements */
    var td_width = 0;
    var th_width = 0;
    $('td').each(function(i,e) {
      if ($(e).width()>td_width) {
        td_width = $(e).width()
      }
    })
    $('tbody th').each(function(i,e) {
      if ($(e).width()>th_width) {
        th_width = $(e).width()
      }
    })
    $("<style>td {width:"+td_width+"px} tbody th {width:"+th_width+"px}</style>").appendTo($('body'))

    /* Colourize the table headings */
    var cols = $('thead th[colspan]').attr('colspan');
    var title = ["blue","orange","green","purple","red","yellow"]
    var sub = title.slice(0,cols);
    title = title.slice(2,4);
    var cycle = 0;
    $('th.header').each(function(i,e){
      $(e).addClass(sub[cycle]);
      cycle++; 
      if (cycle>=cols){
        cycle = 0;
      }
    });
    cycle=0;
    $('thead th[colspan]').each(function(i,e){
      $(e).addClass(title[cycle]);
      cycle++; 
      if (cycle>=2){
        cycle = 0;
      }
    })
  });

</script>
{% endblock %}
{% block fluid_content_outer %}
  <style>
    caption {font-size:large;text-align:left;margin:10px 0}
    table {margin-bottom:40px;}
    table td {text-align:center}
    thead th {text-align:center}
    td a.label {cursor:help}
    .popover .inner {width:500px;}
    td dl.concat {width:120px;}
  </style>
  <div class="fluid-container">
    <div class="content">
      <div class="page-header">
        <h1><a href="{{object.get_absolute_url}}">{{object.name}}</a> results <small>from <a href="{{object.scorecard.project.get_absolute_url}}">{{object.scorecard.project.name}}</a></small></h1>
      </div>
          <h2>Report output</h2>
          {% for key, result in report.items %}
            {% with result.get_values as inner_result %}
              {% if inner_result %}
                <table style="width:auto" class="bordered-table zebra-striped condensed-table">
                <caption>{{key.name}}</caption>
                {% for item in inner_result %}
                  {% if forloop.counter0 == 0 %}
                    <thead>
                      <tr class="titles">
                        <th rowspan=2 style="vertical-align:bottom">{% if item.0.data_type %}{{item.0.data_type}}{% else %}{% for k in item.0 %}{{k.data_type}}{% if forloop.revcounter0 %}, {% endif %}{% endfor %}{% endif %}</th>
                        {% for k, v in item.1 %}
                            <th title="{{k.description}}" colspan="{{v|length}}" style="text-align:center">{{k.name}}</th>
                        {% endfor %}
                      </tr>
                      <tr class="sub_titles">
                        {% if item.1.0.1.0.0 != None %}
                            {% for k, v in item.1 %}
                              {% for ds, value in v %}
                                <th class="header">{{ds.name}}</th>
                              {% endfor %}
                            {% endfor %}
                        {% endif %}
                      </tr>
                    </thead>
                    <tbody>
                  {% endif %}
                    <tr>
                    <th title="{{k.description}}">{{item.0.name}}</th>
                    {% for i, items in item.1 %}
                          {% for series, v in items %}
                            <td>{% if v %}{{v.as_html}}{% endif %}</td>
                          {% endfor %}
                    {% endfor %}
                    </tr>
                {% endfor %}
                  </tbody>
                </table>

              {% else %}
                {% if forloop.counter0 == 0 %}
                  <table style="width:auto" class="bordered-table zebra-striped condensed-table">
                    <thead>
                      <tr>
                        <th rowspan=2 valign=bottom>{% if key.data_type %}{{key.data_type}}{% else %}{% for k in key %}{{k.data_type}}{% if forloop.revcounter0 %}, {% endif %}{% endfor %}{% endif %}</th>
                        {% for k, v in result %}
                            <th title="{{k.description}}" colspan="{{v|length}}" style="text-align:center">{{k.name}}</th>
                        {% endfor %}
                      </tr>
                      <tr>
                        {% if result.0.1.0.0 != None %}
                            {% for k, v in result %}
                              {% for ds, value in v %}
                                <th class="header">{{ds.name}}</th>
                              {% endfor %}
                            {% endfor %}
                        {% endif %}
                      </tr>
                    </thead>
                    <tbody>
                {% endif %}
                <tr>
                  <th title="{{k.description}}" >{{key.name}}</th>
                  {% for i, items in result %}
                        {% for series, v in items %}
                          <td>{% if v %}{{v.as_html}}{% endif %}</td>
                        {% endfor %}
                  {% endfor %}
                </tr>
                {% if forloop.last %}
                  </tbody>
                  </table>
                {% endif %}
              {% endif %}
            {% endwith %}
          {% endfor %}
          </table>
    </div>
  </div>
{% endblock %}

django-scorecard-processor/scorecard_processor/templates/scorecard_processor/responseset_list.html
{% extends 'base.html' %}
{% block head_title %}{{survey}}{% endblock %}
{% block script_bottom %}
{{block.super}}
<script type="text/javascript">
  $('[rel=popover]').popover();
</script>
{% endblock %}
{% block fluid_content_outer %}
  <div class="fluid-container">
    <div class="content">
      <div class="page-header">
        <h1>Responses: {{survey.name}} <small>from <a href="{{survey.project.get_absolute_url}}">{{survey.project.name}}</a></small></h1>
      </div>
      <div class="span5">
        Found <strong>{{count}} result{{count|pluralize}}</strong>
        {% if entity %} for <strong>{{entity.name}}</strong> (<a href="../../">show all</a>){% endif %}
        {% if series %} for <strong>{{series}}</strong> (<a href="../../">show all</a>){% endif %}
        <br />
        Displaying 20 per page
      </div>
      {% include '_pagination.html' %}
      <table class="zebra-striped bordered-table">
        <thead>
          <tr>
            <th>
              <div style="width:120px">Entity</div>
            </th>
            <th>
              <div style="width:120px">Series</div>
            </th>
            {% for question in survey.question_set.all %}
              <th title="{{question.question}}" rel="popover" data-content="{{question.help_text}}"><div style="{% if "text" in question.widget %}min-width:150px{% endif %}" >{{question.identifier}}</div></th>
            {% endfor %}
          </tr>
        </thead>
        <tbody>
      {% for responseset in object_list %}
        <tr>
          <th>
            <div>{{responseset.entity.entity_type.pk}}: <a href="{% url show_survey_responses_entity survey.project.pk survey.pk responseset.entity.pk %}">{{responseset.entity.name}}</a></div>
          </th>
          <th>
            <div>{% for series in responseset.data_series.all %}<a href="{% url show_survey_responses_series survey.project.pk survey.pk series.name %}">{{series.name}}</a>{% if forloop.revcounter0 %}, {% endif %}{% endfor %}</div>
          </th>
          {% for question, response in responseset.get_responses.items %}
            <td><span title="{{question.question}}" data-content="{{response.get_value}}" rel="popover" data-placement="below">{{response.get_value|truncatewords:5}}</td>
          {% endfor %}
        </tr>
      {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
{% endblock %}